In [2]:
import fsspec
import geopandas as gpd

In [5]:
with fsspec.open('https://github.com/scottyhq/snotel/raw/main/snotel-sites.geoparquet') as f:
    gf = gpd.read_parquet(f)

In [6]:
gf.head()

,name,elevation_m,latitude,longitude,county,state,beginDate,endDate,isActive,geometry
code,,,,,,,,,,
301_CA_SNTL,Adin Mtn,1886.712036,41.235828,-120.791924,Modoc,California,1983-10-01,2100-01-01,True,POINT (-120.79192 41.23583)
907_UT_SNTL,Agua Canyon,2712.719971,37.522171,-112.271179,Kane,Utah,1994-10-01,2100-01-01,True,POINT (-112.27118 37.52217)
916_MT_SNTL,Albro Lake,2529.840088,45.597229,-111.959023,Madison,Montana,1996-09-01,2100-01-01,True,POINT (-111.95902 45.59723)
1267_AK_SNTL,Alexander Lake,48.768002,61.749668,-150.889664,Matanuska-Susitna,Alaska,2014-08-28,2100-01-01,True,POINT (-150.88966 61.74967)
908_WA_SNTL,Alpine Meadows,1066.800049,47.779572,-121.698471,King,Washington,1994-09-01,2100-01-01,True,POINT (-121.69847 47.77957)